#!/bin/sh

xrdb -merge ~/.dotfiles/Xresources
xrdb -merge ~/.dotfiles/`hostname`/Xresources
compton -Cb
find -print0 ~/Pictures/background | shuf -z -n1 | xargs -0 feh --bg-fill --no-fehbg

urxvtd -o -f
unclutter &
parcellite &

. ~/.dotfiles/`hostname`/xsession

exec bash --login -c 'TMUX="" SHELL="/bin/bash" ssh-agent dbus-launch --sh-syntax --exit-with-session xmonad'
