#!/bin/sh

xrdb -merge ~/.dotfiles/xresources
xrdb -merge ~/.dotfiles/`hostname`/xresources
compton -Cb

bash --login -c 'urxvtd -o -f'
unclutter &
parcellite &

. ~/.dotfiles/`hostname`/xsession

exec bash --login -c 'TMUX="" SHELL="/bin/bash" dbus-launch --sh-syntax --exit-with-session xmonad'
