#!/bin/sh

#xsetroot -cursor_name left_ptr
xrdb -merge .Xresources
compton -Cb
~/.fehbg
xinput disable 10
qxkb &

urxvtd -o -f
unclutter &
parcellite &

exec bash --login -c 'TMUX="" SHELL="/bin/bash" ssh-agent dbus-launch --sh-syntax --exit-with-session xmonad'
